export enum TestSource {
  BASIC = 'basic',
  ADVANCED = 'advanced',
  UPLOAD = 'upload',
  API = 'api',
  CLI = 'cli',
  AGENT = 'agent',
  UNKNOWN = 'unknown',
}

export class TestConfig {
  test_id: string;
  zip_key?: string;
  name?: string | null;
  description?: string | null;
  source?: TestSource | TestSource.UNKNOWN;
  url?: string;
  test_date?: Date;
  browser?: string;
  created_at: number = Math.floor(Date.now() / 1000);

  constructor() {
    this.test_id = this.generateUUID(); 
  }

  /// <summary>
  /// Create a TestConfig from a config file that is
  /// generated by Telescope agent.
  /// </summary>
  /// <param name="config">The config object</param>
  /// <param name="zipKey">R2 storage key (content hash)</param>
  /// <returns>The TestConfig object</returns>
  static fromConfig(config: Record<string, any>, zipKey?: string): TestConfig {
    const testConfig = new TestConfig();
    testConfig.zip_key = zipKey;
    testConfig.name = config.name || null;
    testConfig.description = config.description || null;
    testConfig.source = config.source || TestSource.UNKNOWN;
    testConfig.url = config.url || '';
    testConfig.test_date = config.date || null;
    testConfig.browser = config.options.browser || '';
    testConfig.created_at =
      Math.floor(new Date(config.date).getTime() / 1000) ||
      Math.floor(Date.now() / 1000);
    return testConfig;
  }

  private generateUUID(): string {
    let date_ob = new Date();
    // adjust 0 before single digit value
    let date = ('0' + date_ob.getDate()).slice(-2);
    let month = ('0' + (date_ob.getMonth() + 1)).slice(-2);
    let year = date_ob.getFullYear();
    let hour = ('0' + date_ob.getHours()).slice(-2);
    let minute = ('0' + date_ob.getMinutes()).slice(-2);
    let second = ('0' + date_ob.getSeconds()).slice(-2);
    return (
      year +
      '_' +
      month +
      '_' +
      date +
      '_' +
      hour +
      '_' +
      minute +
      '_' +
      second +
      '_' +
      generatePseudoRandomUUID()
    );

    function generatePseudoRandomUUID(): string {
      return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(
        /[xy]/g,
        function (c) {
          const r = (Math.random() * 16) | 0;
          const v = c === 'x' ? r : (r & 0x3) | 0x8;
          return v.toString(16);
        },
      );
    }
  }

  async saveToD1(env: any): Promise<any | null> {
    try {
      const stmt = env.TELESCOPE_DB.prepare(`
    INSERT INTO tests (
      test_id,
      zip_key, 
      name, 
      description,
      source,
      url,
      test_date,
      browser,
      created_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);
      await stmt
        .bind(
          this.test_id,
          this.zip_key,
          this.name,
          this.description,
          this.source,
          this.url,
          this.test_date,
          this.browser,
          this.created_at,
        )
        .run();
      return stmt.changes;
    } catch (error) {
      console.error('Failed to save test:', error);
      return null;
    }
  }
}
