export enum TestSource {
    BASIC = 'basic',
    ADVANCED = 'advanced',
    UPLOAD = 'upload',
    API = 'api',
    CLI = 'cli',
    AGENT = 'agent',
    UNKNOWN = 'unknown',
}

export class TestConfig {
    test_id: string;
    name?: string | null;
    description?: string | null;
    source?: TestSource | TestSource.UNKNOWN;
    url?: string;
    test_date?: Date;
    browser?: string;
    owner?: string | null; // user id or email
    created_at: number = Math.floor(Date.now() / 1000);

    constructor() {
        this.test_id = this.generateUUID();
    }

  /// <summary>
  /// Create a TestConfig from a config file that is
  /// generated by Telescope agent.
  /// </summary>
  /// <param name="config">The config object</param>
  /// <returns>The TestConfig object</returns>
  static fromConfig(testId: string, config: Record<string, any>): TestConfig {
    const testConfig = new TestConfig();
    // may need to parse from cli command if available
    testConfig.test_id = testId;
    testConfig.name = config.name || null;
    testConfig.description = config.description || null;
    testConfig.source = config.source || TestSource.UNKNOWN;
    testConfig.url = config.url || '';
    testConfig.test_date = config.test_date || null;
    testConfig.browser = config.options.browser || '';
    testConfig.created_at =
      Math.floor(new Date(config.date).getTime() / 1000) ||
      Math.floor(Date.now() / 1000);
    return testConfig;
  }

  /// <summary>
  /// Create a TestConfig from a input object that is sent to the API
  /// via the web form or the API endpoint directly.
  /// </summary>
  /// <param name="data">The input object</param>
  /// <returns>The TestConfig object</returns>
  static fromInput(data: Record<string, any>): TestConfig {
    const testConfig = new TestConfig();
    testConfig.test_id = testConfig.generateUUID();
    testConfig.name = data.name || null;
    testConfig.description = data.description || null;
    testConfig.source = data.source || TestSource.UNKNOWN;
    testConfig.url = data.url || '';
    testConfig.test_date = data.test_date || null;
    testConfig.browser = data.options.browser || '';
    return testConfig;
  }

  private generateUUID(): string {
    let date_ob = new Date();
    // adjust 0 before single digit value
    let date = ('0' + date_ob.getDate()).slice(-2);
    let month = ('0' + (date_ob.getMonth() + 1)).slice(-2);
    let year = date_ob.getFullYear();
    let hour = ('0' + date_ob.getHours()).slice(-2);
    let minute = ('0' + date_ob.getMinutes()).slice(-2);
    let second = ('0' + date_ob.getSeconds()).slice(-2);
    return (
      year +
      '_' +
      month +
      '_' +
      date +
      '_' +
      hour +
      '_' +
      minute +
      '_' +
      second +
      '_' +
      generatePseudoRandomUUID()
    );

    function generatePseudoRandomUUID(): string {
      return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(
        /[xy]/g,
        function (c) {
          const r = (Math.random() * 16) | 0;
          const v = c === 'x' ? r : (r & 0x3) | 0x8;
          return v.toString(16);
        },
      );
    }
  }

  isValid(): boolean {
    return this.url !== '' && this.browser !== '';
  }

  async saveToD1(env: any): Promise<any | null> {
    try {
      const stmt = env.DB.prepare(`
    INSERT INTO tests (
      test_id, 
      name, 
      description,
      source,
      url,
      test_date,
      browser,
      created_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `);
      await stmt
        .bind(
          this.test_id,
          this.name,
          this.description,
          this.source,
          this.url,
          this.test_date,
          this.browser,
          this.created_at,
        )
        .run();
      return stmt.changes;
    } catch (error) {
      console.error('Failed to save test:', error);
      return null;
    }
  }
}
