import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import process from 'node:process';
import { URL } from 'node:url';

import { format } from 'prettier';

const require = createRequire(import.meta.url);
const bcd = require('@mdn/browser-compat-data');
const outputUrl = new URL('../src/baselineHtmlBcd.ts', import.meta.url);

// BCD nests a small number of behavioral features beside content attributes.
const NON_ATTRIBUTE_ELEMENT_FEATURES = new Set([
  'iframe.cross-origin-top-navigation-by-user-activation',
]);

const compareStrings = (left, right) =>
  left < right ? -1 : left > right ? 1 : 0;

const isElementAttribute = (tag, name) =>
  name !== '__compat' &&
  !name.includes('_') &&
  !NON_ATTRIBUTE_ELEMENT_FEATURES.has(`${tag}.${name}`);

const htmlElementEntries = Object.entries(bcd.html.elements).sort(
  ([left], [right]) => compareStrings(left, right),
);

const elementAttributeEntries = htmlElementEntries.map(([tag, element]) => {
  const attributes = Object.keys(element)
    .filter(name => isElementAttribute(tag, name))
    .map(name => name.toLowerCase())
    .sort(compareStrings);

  return [tag, attributes.join(',')];
});

const attributeBcdNameEntries = htmlElementEntries.flatMap(([tag, element]) =>
  Object.keys(element)
    .filter(name => isElementAttribute(tag, name))
    .filter(name => name !== name.toLowerCase())
    .sort(compareStrings)
    .map(name => [`${tag}.${name.toLowerCase()}`, name]),
);

const globalAttributes = Object.keys(bcd.html.global_attributes)
  .filter(name => name !== 'data_attributes')
  .sort(compareStrings);

const inputTypeValues = Object.keys(bcd.html.elements.input)
  .filter(name => name.startsWith('type_'))
  .sort(compareStrings)
  .map(name => [name.slice('type_'.length), `html.elements.input.${name}`]);

if (!bcd.html.elements.img.loading) {
  throw new Error('Expected html.elements.img.loading in BCD');
}

if (!bcd.html.global_attributes.data_attributes) {
  throw new Error('Expected html.global_attributes.data_attributes in BCD');
}

const valueKeys = {
  'img.loading': {
    lazy: 'html.elements.img.loading',
  },
  'input.type': Object.fromEntries(inputTypeValues),
};

const source = `
// Generated by scripts/generateBaselineHtmlBcd.mjs from MDN BCD ${bcd.__meta.version}.
// Do not edit manually. Run npm run generate:baseline-html-bcd instead.

export const ATTRIBUTE_BCD_NAMES: Readonly<Record<string, string>> = ${JSON.stringify(Object.fromEntries(attributeBcdNameEntries))};

export const CUSTOM_DATA_ATTRIBUTE_BCD_KEY =
  'html.global_attributes.data_attributes';

export const GLOBAL_ATTRIBUTES = ${JSON.stringify(globalAttributes)} as const;

export const HTML_ELEMENT_ATTRIBUTES: Readonly<Record<string, string>> = ${JSON.stringify(Object.fromEntries(elementAttributeEntries))};

export const VALUE_KEYS: Readonly<Record<string, Readonly<Record<string, string>>>> = ${JSON.stringify(valueKeys)};

export const VALUE_ONLY_ATTRIBUTES = ${JSON.stringify(Object.keys(valueKeys).sort(compareStrings))} as const;
`;

const generated = await format(source, {
  parser: 'typescript',
  singleQuote: true,
});

if (process.argv.includes('--check')) {
  const committed = await readFile(outputUrl, 'utf8');
  if (committed !== generated) {
    process.stderr.write(
      'Generated HTML BCD constants are stale. Run npm run generate:baseline-html-bcd.\n',
    );
    process.exitCode = 1;
  }
} else {
  await writeFile(outputUrl, generated);
}
