/**
 * HTML element and content-attribute keys from MDN BCD 8.0.8.
 *
 * Attribute names containing underscores are BCD subfeatures rather than
 * literal content attributes and are intentionally excluded. Values are
 * comma-delimited to keep this generated snapshot compact and reviewable.
 * Pinning this data makes detection independent of the tested browser's own
 * DOM implementation, including for features that browser does not support.
 */
export const HTML_ELEMENT_ATTRIBUTES: Readonly<Record<string, string>> = {
  a: 'attributionsourceid,attributionsrc,charset,coords,download,href,hreflang,hreftranslate,interestfor,name,ping,referrerpolicy,rel,rev,shape,target,type',
  abbr: '',
  acronym: '',
  address: '',
  area: 'alt,attributionsrc,coords,download,href,hreflang,interestfor,nohref,ping,referrerpolicy,rel,shape,target,type',
  article: '',
  aside: '',
  audio:
    'autoplay,controls,controlslist,crossorigin,disableremoteplayback,loading,loop,muted,preload,src',
  b: '',
  base: 'href,target',
  bdi: '',
  bdo: '',
  big: '',
  blockquote: 'cite',
  body: 'alink,background,bgcolor,bottommargin,leftmargin,link,rightmargin,text,topmargin,vlink',
  br: 'clear',
  button:
    'command,commandfor,disabled,form,formaction,formenctype,formmethod,formnovalidate,formtarget,interestfor,name,popovertarget,popovertargetaction,type,value',
  canvas: 'height,moz-opaque,width',
  caption: 'align',
  center: '',
  cite: '',
  code: '',
  col: 'align,char,charoff,span,valign,width',
  colgroup: 'align,char,charoff,span,valign,width',
  data: 'value',
  datalist: '',
  dd: '',
  del: 'cite,datetime',
  details: 'name,open',
  dfn: '',
  dialog: 'closedby,open',
  dir: 'compact',
  div: 'align',
  dl: '',
  dt: '',
  em: '',
  embed: 'align,height,name,src,type,width',
  fencedframe: 'allow,height,width',
  fieldset: 'disabled,form,name',
  figcaption: '',
  figure: '',
  font: 'color,face,size',
  footer: '',
  form: 'accept-charset,action,autocomplete,enctype,method,name,novalidate,rel,target',
  frame: 'frameborder,marginheight,marginwidth,name,noresize,scrolling,src',
  frameset: 'cols,rows',
  geolocation: 'autolocate,watch',
  h1: '',
  h2: '',
  h3: '',
  h4: '',
  h5: '',
  h6: '',
  head: '',
  header: '',
  hgroup: '',
  hr: 'align,color,noshade,size,width',
  html: 'version,xmlns',
  i: '',
  iframe:
    'align,allow,allowfullscreen,allowpaymentrequest,browsingtopics,credentialless,csp,frameborder,height,loading,longdesc,marginheight,marginwidth,name,referrerpolicy,sandbox,scrolling,src,srcdoc,width',
  img: 'align,alt,attributionsrc,border,crossorigin,decoding,fetchpriority,height,hspace,ismap,loading,longdesc,name,referrerpolicy,sizes,src,srcset,usemap,vspace,width',
  input:
    'accept,align,alpha,alt,autocomplete,capture,checked,colorspace,dirname,disabled,form,formaction,formenctype,formmethod,formnovalidate,formtarget,max,maxlength,min,minlength,multiple,name,pattern,placeholder,popovertarget,popovertargetaction,readonly,required,size,src,step,switch,usemap,webkitdirectory',
  ins: 'cite,datetime',
  kbd: '',
  label: 'for',
  legend: 'align',
  li: 'type,value',
  link: 'as,blocking,charset,crossorigin,disabled,fetchpriority,href,hreflang,imagesizes,imagesrcset,integrity,media,referrerpolicy,rel,rev,sizes,target,type',
  main: '',
  map: 'name',
  mark: '',
  marquee:
    'behavior,bgcolor,direction,height,hspace,loop,scrollamount,scrolldelay,truespeed,vspace,width',
  menu: '',
  meta: 'charset,content,http-equiv,name,scheme',
  meter: 'high,low,max,min,optimum,value',
  model: 'autoplay,height,loop,src,stagemode,width',
  nav: '',
  nobr: '',
  noembed: '',
  noframes: '',
  noscript: '',
  object:
    'archive,border,classid,codebase,codetype,data,declare,form,height,name,standby,type,usemap,width',
  ol: 'compact,reversed,start,type',
  optgroup: 'disabled,label',
  option: 'disabled,label,selected,value',
  output: 'for,form,name',
  p: '',
  param: 'name,type,value,valuetype',
  picture: '',
  plaintext: '',
  pre: 'width',
  progress: 'max,value',
  q: 'cite',
  rb: '',
  rp: '',
  rt: '',
  rtc: '',
  ruby: '',
  s: '',
  samp: '',
  script:
    'async,attributionsrc,blocking,crossorigin,defer,fetchpriority,integrity,nomodule,referrerpolicy,src,type',
  search: '',
  section: '',
  select: 'autocomplete,disabled,form,multiple,name,required,size',
  selectedcontent: '',
  slot: 'name',
  small: '',
  source: 'height,media,sizes,src,srcset,type,width',
  span: '',
  strike: '',
  strong: '',
  style: 'blocking,media,type',
  sub: '',
  summary: '',
  sup: '',
  table:
    'align,bgcolor,border,cellpadding,cellspacing,frame,rules,summary,width',
  tbody: 'align,bgcolor,char,charoff,valign',
  td: 'abbr,align,axis,bgcolor,char,charoff,colspan,headers,rowspan,scope,valign,width',
  template:
    'shadowrootclonable,shadowrootcustomelementregistry,shadowrootdelegatesfocus,shadowrootmode,shadowrootreferencetarget,shadowrootserializable,shadowrootslotassignment',
  textarea:
    'autocomplete,cols,dirname,disabled,form,maxlength,minlength,name,placeholder,readonly,required,rows,wrap',
  tfoot: 'align,bgcolor,char,charoff,valign',
  th: 'abbr,align,axis,bgcolor,char,charoff,colspan,headers,rowspan,scope,valign,width',
  thead: 'align,bgcolor,char,charoff,valign',
  time: 'datetime',
  title: '',
  tr: 'align,bgcolor,char,charoff,valign',
  track: 'default,kind,label,src,srclang',
  tt: '',
  u: '',
  ul: 'compact,type',
  var: '',
  video:
    'autoplay,controls,controlslist,crossorigin,disablepictureinpicture,disableremoteplayback,height,loading,loop,muted,playsinline,poster,preload,src,width',
  wbr: '',
  xmp: '',
};
