/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 264dc346a377b80ccef32ba15f4414f7)
interface __BaseEnv_Env {
	RESULTS_BUCKET?: R2Bucket;
	TELESCOPE_DB?: D1Database;
	AI?: Ai;
	ASSETS?: Fetcher;
	ENABLE_AI_RATING?: "false" | "true";
}
declare namespace Cloudflare {
	interface DevelopmentEnv {
		RESULTS_BUCKET: R2Bucket;
		TELESCOPE_DB: D1Database;
		AI: Ai;
		ASSETS: Fetcher;
		ENABLE_AI_RATING: "false";
	}
	interface StagingEnv {
		RESULTS_BUCKET: R2Bucket;
		TELESCOPE_DB: D1Database;
		AI: Ai;
		ASSETS: Fetcher;
		ENABLE_AI_RATING: "true";
	}
	interface ProductionEnv {
		RESULTS_BUCKET: R2Bucket;
		TELESCOPE_DB: D1Database;
		AI: Ai;
		ASSETS: Fetcher;
		ENABLE_AI_RATING: "true";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENABLE_AI_RATING">> {}
}
