// data models related to tests

export enum TestSource {
  BASIC = 'basic',
  ADVANCED = 'advanced',
  UPLOAD = 'upload',
  API = 'api',
  CLI = 'cli',
  AGENT = 'agent',
  UNKNOWN = 'unknown',
}

export class TestConfig {
  test_id: string;
  zip_key: string;
  name?: string | null;
  description?: string | null;
  source: TestSource;
  url: string;
  test_date: number;
  browser: string;
  created_at: number = Math.floor(Date.now() / 1000);
  updated_at: number = Math.floor(Date.now() / 1000);

  /// <summary>
  /// Create a TestConfig from a config file that is
  /// generated by Telescope agent.
  /// </summary>
  /// <param name="config">The config object</param>
  /// <param name="zipKey">R2 storage key (content hash)</param>
  /// <returns>The TestConfig object</returns>
  constructor(config: Record<string, any>, zipKey: string) {
    this.test_id = this.generateTestId();
    this.zip_key = zipKey;
    this.name = config.name || null;
    this.description = config.description || null;
    this.source = config.source || TestSource.UNKNOWN;
    this.url = config.url;
    this.test_date = Math.floor(new Date(config.date).getTime() / 1000);
    this.browser = config.options.browser;
  }

  private generateTestId(): string {
    let date_ob = new Date();
    // adjust 0 before single digit value
    let date = ('0' + date_ob.getDate()).slice(-2);
    let month = ('0' + (date_ob.getMonth() + 1)).slice(-2);
    let year = date_ob.getFullYear();
    let hour = ('0' + date_ob.getHours()).slice(-2);
    let minute = ('0' + date_ob.getMinutes()).slice(-2);
    let second = ('0' + date_ob.getSeconds()).slice(-2);
    return (
      year +
      '_' +
      month +
      '_' +
      date +
      '_' +
      hour +
      '_' +
      minute +
      '_' +
      second +
      '_' +
      self.crypto.randomUUID()
    );
  }
}
