name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Release
    if: ${{ github.repository_owner == 'cloudflare' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    env:
      HOME: /root
    container:
      # make sure to match this version with the one in package.json
      image: mcr.microsoft.com/playwright:v1.59.1-noble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install xz-utils
        run: apt-get update && apt-get install -y xz-utils

      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Install dependencies
        # don't install the browsers since we're using the pre-built container
        run: npm ci --ignore-scripts

      - name: Build telescope
        working-directory: ./packages/telescope
        run: npm run build

      - name: Build telescope-web
        working-directory: ./packages/telescope-web
        run: npm run generate

      - name: Run lint
        working-directory: ./packages/telescope
        run: npm run lint

      - name: Run tests
        working-directory: ./packages/telescope
        run: npm run test:ci

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run version-packages
          publish: npx changeset publish
          commit: 'chore: version packages'
          title: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
